/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "OSMCAL_interface.h"
#include "main.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include <stdio.h>

#define CHANEL1_PORT			PORTC
#define CHANEL1_PIN				PIN8

#define CHANEL2_PORT			PORTC
#define CHANEL2_PIN				PIN6

#define CHANEL3_PORT			PORTC
#define CHANEL3_PIN				PIN5

#define CHANEL4_PORT			PORTC
#define CHANEL4_PIN				PIN9




#define DELAY_COUNT_1MS			1250U
#define DELAY_COUNT_1S			(1000U*DELAY_COUNT_1MS)
void Delay_void(uint32_t Count)
{
	uint32_t i;
	for (i = 0; i < Count; ++i);
}
int main(void)
{
	GPIO_PinConfig_t Chanel1=
	{
			.port= CHANEL1_PORT,
			.pin = CHANEL1_PIN,
			.speed = SPEED_LOW,
			.OutputType = PUSH_PULL,
			.PullType = NOPULL,
			.mode = OUTPUT,
	};
	GPIO_PinConfig_t Chanel2=
		{
				.port= CHANEL2_PORT,
				.pin = CHANEL2_PIN,
				.speed = SPEED_LOW,
				.OutputType = PUSH_PULL,
				.PullType = NOPULL,
				.mode = OUTPUT,
		};
	GPIO_PinConfig_t Chanel3=
		{
				.port= CHANEL3_PORT,
				.pin = CHANEL3_PIN,
				.speed = SPEED_LOW,
				.OutputType = PUSH_PULL,
				.PullType = NOPULL,
				.mode = OUTPUT,
		};
	GPIO_PinConfig_t Chanel4=
		{
				.port= CHANEL4_PORT,
				.pin = CHANEL4_PIN,
				.speed = SPEED_LOW,
				.OutputType = PUSH_PULL,
				.PullType = NOPULL,
				.mode = OUTPUT,
		};

	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOC);
	GPIO_u8PinInit(&Chanel1);
	GPIO_u8PinInit(&Chanel2);
	GPIO_u8PinInit(&Chanel3);
	GPIO_u8PinInit(&Chanel4);


	Stack_voidEnableSystenFaultsExcp();

	STK_voidInit(1000);
	Stack_voidSchedulerStackInit(SECED_STACK_START);
	InitTasksStack();

	Stack_voidChangeToPSP();

	//Stack_voidGoUnprivileged();
	Task1_Handler();
    /* Loop forever */
	for(;;);
}
void Task1_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANEL1_PORT, CHANEL1_PIN);
		TaskDelay(1000);
	}
}
void Task2_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANEL2_PORT, CHANEL2_PIN);
		TaskDelay(500);
	}
}
void Task3_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANEL3_PORT, CHANEL3_PIN);
		TaskDelay(250);
	}
}
void Task4_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANEL4_PORT, CHANEL4_PIN);
		TaskDelay(125);
	}
}
void UsageFault_Handler(void)
{
	while(1);
}
void BusFault_Handler(void)
{
	while(1);
}
void MemManage_Handler(void)
{
	while(1);
}
